from termcolor import colored
import time
def mainMenuNorm():
	print (colored('                            ____________','cyan'))
	time.sleep(x/2)
	print (colored('                            \|M  A  I  N|\ ','cyan'))
	time.sleep(x/2)
	print (colored('                             \|-=-=-=-=-=|\ ','cyan'))
	time.sleep(x/2)
	print (colored('                              \|M  E  N  U|\ ','cyan'))
	time.sleep(x/2)
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|', 'cyan'))
	time.sleep(x)
	print (colored('|   AREA   |||||||| PERIMITER |||||||| SURFACE AREA  ||||||||    VOLUME   ||||||||', 'cyan'))
	time.sleep(x)
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|', 'cyan'))
	time.sleep(x)
	print (colored('|  SQUARE  | 1.01 |   SQUARE  | 2.01 |      CUBE     | 3.01 |     CUBE    | 4.01 |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('| TRIANGLE | 1.02 |  TRIANGLE | 2.02 |  RECTANGULAR  | 3.02 | RECTANGULAR | 4.02 |', 'cyan'))
	time.sleep(x)
	print (colored('|          |      |           |      |     PRISM     |      |    PRISM    |      |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('|  CIRCLE  | 1.03 |   CIRCLE  | 2.03 |   TRIANGULAR  | 3.03 |  TRIANGULAR | 4.03 |', 'cyan'))
	time.sleep(x)
	print (colored('|          |      |           |      |     PRISM     |      |    PRISM    |      |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('|    TBA   | 1.04 |    TBA    | 2.04 |      CONE     | 3.04 |     CONE    | 4.04 |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('|    TBA   | 1.05 |    TBA    | 2.05 |  RECTANGULAR  | 3.05 | RECTANGULAR | 4.05 |', 'cyan'))
	time.sleep(x)
	print (colored('|          |      |           |      |    PYRAMID    |      |  PYRAMID    |      |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('|    TBA   | 1.06 |    TBA    | 2.06 |   TRIANGULAR  | 3.06 |  TRIANGULAR | 4.06 |', 'cyan'))
	time.sleep(x)
	print (colored('|          |      |           |      |    PYRAMID    |      |   PYRAMID   |      |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('|    TBA   | 1.07 |    TBA    | 2.07 |     SPHERE    | 3.07 |    SPHERE   | 4.07 |', 'cyan'))
	time.sleep(x)
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	time.sleep(x)
	print (colored('|    TBA   | 1.08 |    TBA    | 2.08 |    CYLINDER   | 3.08 |   CYLINDER  | 4.08 |', 'cyan'))
	time.sleep(x)
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|', 'cyan'))
	time.sleep(x)
	print (colored('|      OTHER      ||||||||||     OTHER EQUATIONS     ||||||||','cyan'))
	time.sleep(x)
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=|||=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=|','cyan'))
	time.sleep(x)
	print (colored('|     VARIBLES    | 0.01 |||    PYTHAGOREAN THEROM   | 5.01 |','cyan'))
	time.sleep(x)
	print (colored('|   TRANSLATION   |      |||++++++++++++++++++++++++++++++++|','cyan'))
	time.sleep(x)
	print (colored('|++++++++++++++++++++++++|||      SIMPLE INTREST     | 5.02 |','cyan'))
	time.sleep(x)
	print (colored('| EQUATIONS  USED | 0.02 |||++++++++++++++++++++++++++++++++|','cyan'))
	time.sleep(x)
	print (colored('|++++++++++++++++++++++++|||     COMPOUND INTREST    | 5.03 |','cyan'))
	time.sleep(x)
	print (colored('|       EXIT      | 0.03 |||++++++++++++++++++++++++++++++++|','cyan'))
	time.sleep(x)
	print (colored('|++++++++++++++++++++++++|||           TBA           | 5.04 |','cyan'))
	time.sleep(x)
	print (colored('|     SHOW MENU   | 0.04 |||++++++++++++++++++++++++++++++++|','cyan'))
	time.sleep(x)
	print (colored('|++++++++++++++++++++++++|||           TBA           | 5.05 |','cyan'))
	time.sleep(x)
	print (colored('|     SETTINGS    | 0.05 |||=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-|','cyan'))
	time.sleep(x)
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=|||','cyan'))
	time.sleep(x)
def mainMenuNoSleep():
	print('wip')
	print (colored('                            ____________','cyan'))
	print (colored('                            \|M  A  I  N|\ ','cyan'))
	print (colored('                             \|-=-=-=-=-=|\ ','cyan'))
	print (colored('                              \|M  E  N  U|\ ','cyan'))
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|', 'cyan'))
	print (colored('|   AREA   |||||||| PERIMITER |||||||| SURFACE AREA  ||||||||    VOLUME   ||||||||', 'cyan'))
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|', 'cyan'))
	print (colored('|  SQUARE  | 1.01 |   SQUARE  | 2.01 |      CUBE     | 3.01 |     CUBE    | 4.01 |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('| TRIANGLE | 1.02 |  TRIANGLE | 2.02 |  RECTANGULAR  | 3.02 | RECTANGULAR | 4.02 |', 'cyan'))
	print (colored('|          |      |           |      |     PRISM     |      |    PRISM    |      |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('|  CIRCLE  | 1.03 |   CIRCLE  | 2.03 |   TRIANGULAR  | 3.03 |  TRIANGULAR | 4.03 |', 'cyan'))
	print (colored('|          |      |           |      |     PRISM     |      |    PRISM    |      |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('|    TBA   | 1.04 |    TBA    | 2.04 |      CONE     | 3.04 |     CONE    | 4.04 |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('|    TBA   | 1.05 |    TBA    | 2.05 |  RECTANGULAR  | 3.05 | RECTANGULAR | 4.05 |', 'cyan'))
	print (colored('|          |      |           |      |    PYRAMID    |      |  PYRAMID    |      |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('|    TBA   | 1.06 |    TBA    | 2.06 |   TRIANGULAR  | 3.06 |  TRIANGULAR | 4.06 |', 'cyan'))
	print (colored('|          |      |           |      |    PYRAMID    |      |   PYRAMID   |      |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('|    TBA   | 1.07 |    TBA    | 2.07 |     SPHERE    | 3.07 |    SPHERE   | 4.07 |', 'cyan'))
	print (colored('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|', 'cyan'))
	print (colored('|    TBA   | 1.08 |    TBA    | 2.08 |    CYLINDER   | 3.08 |   CYLINDER  | 4.08 |', 'cyan'))
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|', 'cyan'))
	print (colored('|      OTHER      ||||||||||     OTHER EQUATIONS     ||||||||','cyan'))
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=|||=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=|','cyan'))
	print (colored('|     VARIBLES    | 0.01 |||    PYTHAGOREAN THEROM   | 5.01 |','cyan'))
	print (colored('|   TRANSLATION   |      |||++++++++++++++++++++++++++++++++|','cyan'))
	print (colored('|++++++++++++++++++++++++|||      SIMPLE INTREST     | 5.02 |','cyan'))
	print (colored('| EQUATIONS  USED | 0.02 |||++++++++++++++++++++++++++++++++|','cyan'))
	print (colored('|++++++++++++++++++++++++|||     COMPOUND INTREST    | 5.03 |','cyan'))
	print (colored('|       EXIT      | 0.03 |||++++++++++++++++++++++++++++++++|','cyan'))
	print (colored('|++++++++++++++++++++++++|||           TBA           | 5.04 |','cyan'))
	print (colored('|     SHOW MENU   | 0.04 |||++++++++++++++++++++++++++++++++|','cyan'))
	print (colored('|++++++++++++++++++++++++|||           TBA           | 5.05 |','cyan'))
	print (colored('|     SETTINGS    | 0.05 |||=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-|','cyan'))
	print (colored('|++++++++++++++++++++++++|||','cyan'))
	print (colored('| CONVERSION MENU | 0.06 |||','cyan'))
	print (colored('|++++++++++++++++++++++++|||','cyan'))
	print (colored('|   CLEAR SCREEN  | 0.07 |||','cyan'))
	print (colored('|-=-=-=-=-=-=-=-=-=-=-=-=|||','cyan'))
